export const RUNNER_TIME_SLICE_MS = 14;

export const RUNNER_CONSERVATIVE_CHUNKS_PER_THREAD = 6;

export const RUNNER_CONSERVATIVE_MAX_DISPATCH_CHUNK = 250;

export const RUNNER_EXTREME_MIN_DISPATCH_CHUNK = 5000;

export const RUNNER_EXTREME_MIN_WORKER_PROGRESS_STRIDE = 5000;

export const RUNNER_CONSERVATIVE_PROGRESS_STRIDE = 100;

export const RUNNER_EXTREME_MAX_WORKER_PROGRESS_STRIDE = 20_000;

export const RUNNER_SEED_SPACE = 0x100000000;
